### ISSUE TITLE
Time limit error for salmon rule in a slurm cluster

### ISSUE THREAD

**Issue by MbDiop** [tdayris-perso/rna-count-salmon#5]
I have tried several times to run salmon but it fails for one sample because the pipeline default time limit is too short (75 min). 

- I have removed the `--time` in slurm sbatch command and the job has failed again because the default queue (shortq) with 6 hours time limit is too short for my job. 

- I have tried to set a value of 30 for `--attempt` (~ 9 hours) and I have observed two problems : 
        1. The memory is also inscreased and I don't want to increase the memory
        2. My job has been submitted to the shortq (default) instead of the mediumq and my job stays in pending state with the reason `partitionTimeLimit`.

**Comment by tdayris-perso** [comment]
Hi,

1. The pipeline do, indeed, increase both memory and time with the `--attempt` parameter. This is the expected behaviour.
2. Snakemake cannot and will never decide the best partition to use by itself. It is up to the [profiles](https://github.com/tdayris-perso/slurm).

I can set-up a user-define time-reservation-increase in the configuration file. Is that what you'd like ?

**Comment by tdayris-perso** [comment]
Anyway, now the time reservation in Salmon is 1h/attempt. Memory reservation increases from 7gb, by 5gb / attempt, with a maximum value of 20gb. Does it suit you?

**Comment by MbDiop** [comment]
Yes, perfect !

**Comment by tdayris-perso** [comment]
So let be commit number [432f90b](https://github.com/tdayris-perso/rna-count-salmon/commit/432f90bc5c1fa652027a3a24b61880abedf5f3a2)
